//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API2_Consuming_WCF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Bext_Sample")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CapitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Capital {
            get {
                return this.CapitalField;
            }
            set {
                if ((object.ReferenceEquals(this.CapitalField, value) != true)) {
                    this.CapitalField = value;
                    this.RaisePropertyChanged("Capital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDep", ReplyAction="http://tempuri.org/IService1/GetDepResponse")]
        WEB_API2_Consuming_WCF.ServiceReference1.Department[] GetDep();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDep", ReplyAction="http://tempuri.org/IService1/GetDepResponse")]
        System.Threading.Tasks.Task<WEB_API2_Consuming_WCF.ServiceReference1.Department[]> GetDepAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertDep", ReplyAction="http://tempuri.org/IService1/InsertDepResponse")]
        void InsertDep(WEB_API2_Consuming_WCF.ServiceReference1.Department pobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertDep", ReplyAction="http://tempuri.org/IService1/InsertDepResponse")]
        System.Threading.Tasks.Task InsertDepAsync(WEB_API2_Consuming_WCF.ServiceReference1.Department pobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateDep", ReplyAction="http://tempuri.org/IService1/UpdateDepResponse")]
        void UpdateDep(WEB_API2_Consuming_WCF.ServiceReference1.Department pobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateDep", ReplyAction="http://tempuri.org/IService1/UpdateDepResponse")]
        System.Threading.Tasks.Task UpdateDepAsync(WEB_API2_Consuming_WCF.ServiceReference1.Department pobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteDep", ReplyAction="http://tempuri.org/IService1/DeleteDepResponse")]
        void DeleteDep(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteDep", ReplyAction="http://tempuri.org/IService1/DeleteDepResponse")]
        System.Threading.Tasks.Task DeleteDepAsync(string Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WEB_API2_Consuming_WCF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WEB_API2_Consuming_WCF.ServiceReference1.IService1>, WEB_API2_Consuming_WCF.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WEB_API2_Consuming_WCF.ServiceReference1.Department[] GetDep() {
            return base.Channel.GetDep();
        }
        
        public System.Threading.Tasks.Task<WEB_API2_Consuming_WCF.ServiceReference1.Department[]> GetDepAsync() {
            return base.Channel.GetDepAsync();
        }
        
        public void InsertDep(WEB_API2_Consuming_WCF.ServiceReference1.Department pobj) {
            base.Channel.InsertDep(pobj);
        }
        
        public System.Threading.Tasks.Task InsertDepAsync(WEB_API2_Consuming_WCF.ServiceReference1.Department pobj) {
            return base.Channel.InsertDepAsync(pobj);
        }
        
        public void UpdateDep(WEB_API2_Consuming_WCF.ServiceReference1.Department pobj) {
            base.Channel.UpdateDep(pobj);
        }
        
        public System.Threading.Tasks.Task UpdateDepAsync(WEB_API2_Consuming_WCF.ServiceReference1.Department pobj) {
            return base.Channel.UpdateDepAsync(pobj);
        }
        
        public void DeleteDep(string Id) {
            base.Channel.DeleteDep(Id);
        }
        
        public System.Threading.Tasks.Task DeleteDepAsync(string Id) {
            return base.Channel.DeleteDepAsync(Id);
        }
    }
}
